import type { Role } from './types';

/** Newest first. `since` is the sort key and the timeline axis label source. */
export const roles: Role[] = [
  {
    id: 'ledger',
    title: 'Co-Founder & Full-Stack Engineer',
    org: 'Ledger',
    location: 'San Diego, CA',
    start: 'Aug 2026',
    end: 'Present',
    since: '2026-08',
    current: true,
    track: 'swe',
    summary:
      'Co-founded a subscription personal finance platform and own most of the stack, from Postgres schema to onboarding UX.',
    points: [
      'Built the product on Next.js 16 (App Router), Supabase Postgres and Auth, TypeScript, Tailwind, and Recharts, deployed on Vercel with a daily bank-sync cron.',
      'Integrated Plaid, SnapTrade, and Kraken for transaction, investment, and liability sync across 76 versioned SQL migrations.',
      'Shipped skippable, resumable first-login onboarding: six interest-driven setup paths that write real records through idempotent server actions.',
      'Implemented row-level security, field-level encryption at rest with pgcrypto, TOTP and WebAuthn MFA, household sharing, and a read-only personal API.',
      'Built navigation loading UX across 12 app routes with page skeletons, link-pending indicators, and enter animations that respect prefers-reduced-motion.',
    ],
    stack: ['Next.js 16', 'TypeScript', 'Supabase', 'Postgres', 'Tailwind', 'Plaid', 'Vercel'],
    metric: { value: '76', label: 'versioned SQL migrations' },
  },
  {
    id: 'civicom',
    title: 'Full-Stack Software Development Engineer',
    org: 'Civicom, Inc.',
    orgNote: 'Welcomeware',
    location: 'Remote',
    start: 'Feb 2026',
    end: 'Present',
    since: '2026-02',
    current: true,
    track: 'swe',
    summary:
      'Lead REST API and EMR integration work for HIPAA-compliant healthcare kiosk and patient check-in software.',
    points: [
      'Own RESTful API development and EMR integration pipelines in Java with Hibernate, MySQL, Vue, AWS, and Jenkins; integrations are the primary driver of new sales.',
      'Built automated document capture with OCR (OpenCV, Tesseract) that reads insurance cards and driver licenses at patient intake.',
      'Built internal tooling to make each additional EMR partnership cheaper than the last.',
      'Design and customise agentic AI workflows on a lean team: subagents, system prompt design, and custom tools injected into agent context.',
    ],
    stack: ['Java', 'Hibernate', 'MySQL', 'Vue', 'AWS', 'Jenkins', 'OpenCV', 'Tesseract'],
    metric: { value: '+67%', label: 'unit revenue YoY, Q3' },
  },
  {
    id: 'fullcryo',
    title: 'Data Scientist',
    org: 'Fullcryo Technology',
    location: 'Remote',
    start: 'Mar 2025',
    end: 'Jan 2026',
    since: '2025-03',
    current: false,
    track: 'ds',
    summary:
      'Built the internal data collection layer and acted as the analytics liaison to the executive team.',
    points: [
      'Built internal data-collection infrastructure spanning logistics, market research, and customer growth.',
      'Ran market analyses for an international expansion campaign that contributed to a 13.2% increase in lead discovery.',
      'Fine-tuned domain-specific conversational models for sales rep and employee support.',
      'Served as primary analytics liaison to executives, translating findings into decisions.',
    ],
    stack: ['Python', 'Pandas', 'SQL', 'LLM fine-tuning'],
    metric: { value: '+13.2%', label: 'lead discovery' },
  },
  {
    id: 'sdge',
    title: 'Data Science Fellow',
    org: 'San Diego Gas & Electric',
    location: 'San Diego, CA',
    start: 'Sept 2024',
    end: 'Mar 2025',
    since: '2024-09',
    current: false,
    track: 'ds',
    summary:
      'Analysed the regional EV charging network and modelled the revenue lost to unreported faults.',
    points: [
      'Analysed 19,700+ EV chargers with time-series and geospatial methods in Pandas, GeoPandas, and Scikit-learn.',
      'Built ingestion pipelines against the Alternative Fuels Data Center API.',
      'Ran regression on DMV registration data with SQL and Statsmodels, projecting up to $825,000 per month in recoverable revenue.',
      'Presented findings to SDG&E stakeholders alongside the capstone fault-detection system.',
    ],
    stack: ['Python', 'Pandas', 'GeoPandas', 'Scikit-learn', 'Statsmodels', 'SQL'],
    metric: { value: '19.7k', label: 'chargers analysed' },
  },
  {
    id: 'hkust',
    title: 'Data Scientist',
    org: 'Hong Kong University of Science and Technology',
    location: 'Hong Kong',
    start: 'June 2024',
    end: 'Oct 2024',
    since: '2024-06',
    current: false,
    track: 'ds',
    summary:
      'Built the pipeline and computer vision models behind an automated video annotation tool.',
    points: [
      'Built an ETL pipeline ingesting over 2TB across 2,500+ promotional videos in mixed formats.',
      'Automated shot classification (panning, zooming, tilt), scene detection and timestamping, and textual scene annotation.',
      'Trained, tested, and validated computer vision models on the curated dataset with PyTorch and OpenCV.',
      'Gathered continuous feedback from end users and shipped usability improvements against it.',
    ],
    stack: ['Python', 'PyTorch', 'OpenCV', 'ETL'],
    metric: { value: '2TB+', label: 'video ingested' },
  },
  {
    id: 'wizard-tower',
    title: 'Data Engineer',
    org: 'Wizard Tower',
    location: 'San Diego, CA',
    start: 'Oct 2023',
    end: 'Jan 2025',
    since: '2023-10',
    current: false,
    track: 'ds',
    summary:
      'First engineering job: built the data flow and observability stack for a small game studio.',
    points: [
      'Built pipelines for staging, deployment, user logging, and metrics analytics in a fast-moving startup.',
      'Built dashboards tracking user activity, engagement, and server performance in real time for leadership.',
      'Researched and stood up the internal data stack, including Google Cloud Run and Grafana Loki.',
      'Oversaw public user-testing deployments and reported on KPIs for each live testing stage.',
    ],
    stack: ['Python', 'Google Cloud Run', 'Grafana Loki', 'SQL'],
  },
];

export const currentRoles = roles.filter((role) => role.current);
