import type { SkillGroup } from './types';

export const skillGroups: SkillGroup[] = [
  {
    id: 'languages',
    label: 'Languages',
    track: 'both',
    items: ['TypeScript', 'JavaScript', 'Python', 'SQL', 'Java', 'C/C++/C#', 'R', 'HTML/CSS'],
  },
  {
    id: 'frontend',
    label: 'Front-end',
    track: 'swe',
    items: ['React', 'Next.js (App Router)', 'Vue', 'Tailwind', 'GSAP', 'Three.js', 'D3.js', 'Recharts'],
  },
  {
    id: 'backend',
    label: 'Back-end',
    track: 'swe',
    items: [
      'Node.js',
      'Supabase / Postgres',
      'MySQL',
      'Java + Hibernate',
      'REST APIs',
      'Server actions',
      'Row-level security',
      'Webhooks',
      'MongoDB',
    ],
  },
  {
    id: 'ml',
    label: 'Data & ML',
    track: 'ds',
    items: [
      'Pandas',
      'Polars',
      'NumPy',
      'PyTorch',
      'Scikit-learn',
      'TensorFlow / Keras',
      'XGBoost',
      'Hugging Face Transformers',
      'OpenCV',
      'GeoPandas',
      'Statsmodels',
    ],
  },
  {
    id: 'methods',
    label: 'Methods',
    track: 'ds',
    items: [
      'Statistical testing and inference',
      'Time-series analysis',
      'Geospatial analysis',
      'Semantic segmentation',
      'Model training and hyperparameter search',
      'Feature engineering',
      'Metric construction',
      'ETL pipeline design',
      'Data annotation workflows',
    ],
  },
  {
    id: 'infra',
    label: 'Cloud & infra',
    track: 'both',
    items: [
      'AWS (EC2, S3, Lambda, DynamoDB)',
      'Vercel',
      'Google Cloud Run',
      'Docker',
      'Jenkins CI/CD',
      'GitHub Actions',
      'Grafana / Loki',
      'Spark',
      'Kubernetes',
    ],
  },
  {
    id: 'integrations',
    label: 'Integrations',
    track: 'swe',
    items: [
      'Plaid',
      'SnapTrade',
      'Kraken',
      'EMR / healthcare data exchange',
      'Vonage and Janus WebRTC',
      'OCR (OpenCV, Tesseract)',
      'Segments.ai',
    ],
  },
  {
    id: 'practice',
    label: 'Practice',
    track: 'both',
    items: [
      'HIPAA-constrained delivery',
      'Agentic AI workflows and custom tooling',
      'Data visualisation',
      'Agile on small teams',
      'Tableau / Power BI',
      'Git',
    ],
  },
];

export const skillFilters = [
  { id: 'all' as const, label: 'Everything' },
  { id: 'ds' as const, label: 'Data / ML' },
  { id: 'swe' as const, label: 'Engineering' },
];
